// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    Cover: typeof import('./src/components/cover.vue')['default']
    Play: typeof import('./src/components/play.vue')['default']
    Scroll: typeof import('./src/components/scroll.vue')['default']
    Select: typeof import('./src/components/select.vue')['default']
    Start: typeof import('./src/components/start.vue')['default']
  }
}
