// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AProgress: typeof import('ant-design-vue/es')['Progress']
    Cover: typeof import('./src/components/cover.vue')['default']
    Start: typeof import('./src/components/start.vue')['default']
  }
}
